package ai.instavision.sandbox.data.notifications

import android.app.NotificationChannel
import android.app.NotificationManager
import android.content.Context
import androidx.core.app.NotificationManagerCompat

/** The identity and behaviour of one notification channel, mirroring production's config object. */
internal data class NotificationChannelConfig(
  val id: String,
  val name: String,
  val description: String,
  val importance: Int,
)

/**
 * Creates the channels the sample posts to and hands out the config each notification type belongs
 * on.
 *
 * The split follows production: ordinary events stay at default importance while doorbell and
 * alarm get channels of their own at [NotificationManager.IMPORTANCE_HIGH], so the user can mute
 * activity without losing the two cases that demand attention. Production also gives those two
 * channels bundled sound files; the sample ships no `res/raw`, so they keep the system default.
 */
internal object NotificationChannels {
  /** Ordinary camera activity, quiet enough to be ignored. */
  val events = NotificationChannelConfig(
    id = "event_notifications_channel",
    name = "Events",
    description = "Events generated by the camera",
    importance = NotificationManager.IMPORTANCE_DEFAULT,
  )

  /** Doorbell presses, which the user is expected to answer straight away. */
  val doorbell = NotificationChannelConfig(
    id = "doorbell_notifications_channel",
    name = "Doorbell",
    description = "Doorbell rings",
    importance = NotificationManager.IMPORTANCE_HIGH,
  )

  /** Security alarms and the monitoring centre's follow-up. */
  val alarm = NotificationChannelConfig(
    id = "alarm_notifications_channel",
    name = "Alarms",
    description = "Alarms raised by the security system",
    importance = NotificationManager.IMPORTANCE_HIGH,
  )

  /** The channel a payload of [type] is posted on. */
  fun configFor(type: NotificationType): NotificationChannelConfig = when (type) {
    NotificationType.Event -> events
    NotificationType.DoorbellRing -> doorbell
    NotificationType.AlarmEvent, NotificationType.AlarmNotified -> alarm
  }

  /** Registers every channel; idempotent, so calling it on each process start is correct. */
  fun create(context: Context) {
    NotificationManagerCompat.from(context).createNotificationChannels(
      listOf(events, doorbell, alarm).map(::channel),
    )
  }

  /** Turns a config into the platform channel, adding the alerting extras above default importance. */
  private fun channel(config: NotificationChannelConfig): NotificationChannel =
    NotificationChannel(config.id, config.name, config.importance).apply {
      description = config.description
      if (config.importance >= NotificationManager.IMPORTANCE_HIGH) {
        enableLights(true)
        enableVibration(true)
      }
    }
}
